#!/bin/bash

# Script that checks the current status of the daily backup job

# Exit codes
ERR_UNLOCKED=0 # aka "Success"
ERR_PROC_RUNNING=1
ERR_PROC_DEAD=2
ERR_GENERAL=3 # General fault
FMRI_DAILY="svc:/system/filesystem/zfs/auto-snapshot:daily"
FMRI_HOURLY="svc:/system/filesystem/zfs/auto-snapshot:hourly"

function check_backup_lock {
    local fmri=$1
    echo fmri is $fmri

    # Output from svccfg looks like this
    # zfs/backup-lock  astring  "incremental_mbuffered backup in progress by PID 23310"
    local status=$(/usr/sbin/svccfg -s $fmri listprop zfs/backup-lock)
    status=$(echo "$status" | sed -e 's/zfs\/backup-lock  astring  //' -e 's/\"//g')
    #echo $status

    if echo $status | grep unlocked > /dev/null; then
        echo "Unlocked"
        return $ERR_UNLOCKED
    else
        backup_type=$(echo $status | awk '{print $1}')
        lockpid=$(echo $status | awk '{print $7}')
        echo Lock held by PID $lockpid running backup type $backup_type
        ps -p $lockpid > /dev/null
        err=$?
        if [[ $err != 0 ]]; then
            echo Process $lockpid is dead.
            return $ERR_PROC_DEAD
        else
            echo Process $lockpid is currently running.
            ptree $lockpid
            return $ERR_PROC_RUNNING
        fi
    fi
}

case $1 in
    daily|"") SvcFmri=$FMRI_DAILY;;
    hourly) SvcFmri=$FMRI_HOURLY;;
    *) echo "Usage: $0 daily|hourly" 1>&2; exit $ERR_GENERAL;;
esac

[ -e /usr/sbin/svccfg ] || ( echo "Can't find svccfg" 1>&2; exit $ERR_GENERAL )

# FMRI of the service we're checking
check_backup_lock $SvcFmri
